Description: ""
name_exp: "mediapipe"

parent_folder: "/andromeda/shared/reco-pomigliano/tempo-gnn/tgcn/"
video_path: "data/PartA/"
csv_file: "data/PartA/samples.csv"
labels_path: "data/PartA/lables.npy"

landmarks_path: "PartA/Mediapipe/dataset_mediapipe_without_process.npy"

data_path: "data/PartA/Mediapipe/dataset_mediapipe.npy"

edges_path: "data/PartA/Mediapipe/edges_mediapipe.npy"

idx_train: "data/PartA/idx_train_filterd_low_react.npy"
idx_test: "data/PartA/idx_test_filterd_low_react.npy"

filter_idx_90: "data/PartA/idx_low_confidance_90.npy"
filter_idx_80: "data/PartA/idx_low_confidance_80.npy"

###Optimizer###
weight_decay: 0.7
step_decay: 30
optimizer: 'SGD'

###Network###
num_epoch: 500 
batch_size: 64
continue_training: False   #If set True will continue training from pretrained model
pretrain_model: ""       #Name of folder that contains the model to resume training
gpu: 1


###Network###
num_epoch: 500 
batch_size: 64
continue_training: False   #If set True will continue training from pretrained model
pretrain_model: "None" #"08-05-17:36" # #"08-03-12:18"       #Name of folder that contains the model resume training
gpu: 0

###Model parameters###
model_name: "aagcn" #"a3tgcn" #
embed_dim: 128
num_subset: 2
num_features: 6
t_kernel_size: 9
hidden_size: 1
TS: 137
n_joints: 468
adaptive: False
lr: 0.01
LOG_DIR: "log/"

