Description: " train on small data set from 20 sample"

name_exp: "dlib"

parent_folder: "/andromeda/shared/reco-pomigliano/tempo-gnn/tgcn/"
video_path: "data/PartA/"
landmarks_path : "data/PartA/3dlandmarks/"
csv_file: "data/PartA/samples.csv"
labels_path: "data/PartA/lables.npy"

data_path: "data/PartA/mediapipe/dataset_mediapipe.npy"
edges_path: "data/PartA/mediapipe/edges_mediapipe.npy" 

idx_train: "data/PartA/minidata/idx_train.npy"
idx_test: "data/PartA/minidata/idx_test.npy"


weight_decay: 0.7
momentum: 0.9
step_decay: 30
L2: 0.0001
optimizer_name: 'SGD'

batch_size: 32
continue_training: False   #If set True will continue training from pretrained model
pretrain_model: "None" #"08-05-17:36" # #"08-03-12:18" #Name of folder that contains the model resume training
Temporal_downsampling: False
model_name: "aagcn" # "a3tgcn" # # #
embed_dim: 128
gru: 1
bn: True
lr: 0.01

num_subset: 2
num_features: 6
hidden_size: 1
N_sample: 8700
TS: 137
n_joints: 478 #51
###Optimizer###
t_kernel_size: 15
strid: 1
normalize_labels: False

adaptive: False
attention: True
drop_out: 0.2
protocol: "hold_out" #"hold_out" #"loso"  
maxMinNormalization: True #False #True

center_loss: False
augmentaion: False #True #False #  # True
prop: #1 # 1 #usando la classe di augmentation.
Aug_type: None #"all" #"all" #"r+f" #"all" # #"r+f" #"f" # [ "r" , "f" , "r+f","all"] None
concatenate: False # True #True #True # # # True
project_name: "pain_estimation_Jul"
log_name: "hold_out_binary_bidirectional_gru_1g" 
gpu: 1
num_classes: 2
num_epoch: 70

eval_loso: False