

description: ""
name_exp : "dlib"
parent_folder: "/Users/fatemahalhamdoosh/Desktop/Git/PAIN_ESTIMATION/"
folder_data_path: "data/PartB/"
video_path: "data/PartB/video/"
landmarks_path : "data/PartB/3dlandmarks/"
landmarks_npy: "data/PartB/landmarksnpy/"
csv_file: "data/PartB/samples.csv"
labels_path: "data/PartB/lables.npy"
data_path: "data/PartB/openFace/dataset_openFace_new.npy" 




edges_path: "data/PartB/openFace/edge_openFace.npy"
filter_idx_90: "data/PartB/idx_low_confidance_90.npy"
filter_idx_80: "data/PartB/idx_low_confidance_80.npy"

# "data/PartB/idx_train_filterd_low_react.npy" 
#idx_train_all_subject
#idx_train_filterd_low_react
#idx_train_filterd
# "data/PartB/idx_test_filterd_low_react.npy"

weight_decay: 0.7
momentum: 0.9
step_decay: 30
L2: 0.0001
optimizer_name: 'SGD'

batch_size: 32
continue_training: False   #If set True will continue training from pretrained model
pretrain_model: "None" #"08-05-17:36" # #"08-03-12:18" #Name of folder that contains the model resume training
Temporal_downsampling: False
model_name: "aagcn" # "a3tgcn" # # #
embed_dim: 128
gru: 2
bn: True
lr: 0.01

num_subset: 2
num_features: 4
hidden_size: 1
TS: 137
n_joints: 51
idx_train:  "data/PartB/idx_train_filterd_low_react.npy" #  #"data/PartB/idx_train_filterd.npy"
idx_test:  "data/PartB/idx_test_filterd_low_react.npy" # #"data/PartB/idx_test_filterd.npy"
LOG_DIR: "log/"
t_kernel_size: 15
strid: 1
normalize_labels: False

adaptive: False
attention: True
drop_out: 0.2
protocol: "hold_out" #"hold_out" #"loso"  
maxMinNormalization: True #False #True

center_loss: False
augmentaion: False #True #False #  # True
prop: #1 # 1 #usando la classe di augmentation.
Aug_type: #"all" #"all" #"r+f" #"all" # #"r+f" #"f" # [ "r" , "f" , "r+f","all"] None
concatenate: False # True #True #True # # # True
project_name: "pain_estimation"
log_name: "hold_out_multi_4Features" #"1s+15k+multi+loso-filtred_LE_test0" minMaxNorm_dx_dy_
gpu: 0
num_classes: 5
num_epoch: 100

eval_loso: False